
version: '3.2'

networks:
    hlf_multi_host_network:
        external: 
            name: hlf_multi_host_network

services:

    ca_org2:
        networks:
            hlf_multi_host_network:
                aliases:
                    - ca_org2
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == ip-172-31-11-143
                    - engine.labels.aws.region == ap-south-1
        image: hyperledger/fabric-ca:amd64-1.4.4
        hostname: ca.org2.example.com
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca_org2
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
            - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/f7c1d1ca44556acfed91b71aa30d9af51abab8054fa663e20964b9da341edb71_sk
        ports:
            - "8054:7054"   
        command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
        volumes:
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config

    couchdb0_org2:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == ip-172-31-11-143
                    - engine.labels.aws.region == ap-south-1
        image: hyperledger/fabric-couchdb:amd64-0.4.18
        hostname: couchdb0_org2
        ports:
           - 7984:5984
        networks:
           - hlf_multi_host_network

    couchdb1_org2:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == ip-172-31-11-143
                    - engine.labels.aws.region == ap-south-1
        image: hyperledger/fabric-couchdb:amd64-0.4.18
        hostname: couchdb1_org2
        ports:
           - 8984:5984
        networks:
           - hlf_multi_host_network
