
version: '3.2'

networks:
    hlf_multi_host_network:
        external: 
            name: hlf_multi_host_network

services:

    peer0_org3:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == ip-172-31-1-154
                    - engine.labels.aws.region == ap-south-1
        image: hyperledger/fabric-peer:amd64-1.4.4
        hostname: peer0.org3.example.com
        environment:
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_PEER_NETWORKID=hlf_multi_host_network
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hlf_multi_host_network
            - CORE_PEER_ADDRESSAUTODETECT=true
            # - CORE_PEER_GOSSIP_ORGLEADER=false
            # - CORE_PEER_GOSSIP_USELEADERELECTION=true
            - CORE_PEER_PROFILE_ENABLED=true
            - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
            #- CORE_LEDGER_STATE_STATEDATABASE=LevelDB
            - FABRIC_LOGGING_SPEC=INFO
            - CORE_LOGGING_GOSSIP=${CORE_LOGGING_GOSSIP}
            - CORE_LOGGING_MSP=CRITICAL
            # - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
            # TLS settings
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
            - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
            - CORE_PEER_CHAINCODELISTENADDRESS=peer0.org3.example.com:7052
            - CORE_PEER_ID=peer0.org3.example.com
            - CORE_PEER_ADDRESS=peer0.org3.example.com:7051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.example.com:7051
            - CORE_PEER_LOCALMSPID=Org3MSP
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0_org3:5984
            - CORE_CHAINCODE_LOGGING_LEVEL=info
            - CORE_CHAINCODE_LOGGING_SHIM=info
        volumes:
            - /var/run/:/host/var/run/
            # - $GOPATH/src/github.com/hyperledger/fabric/:/opt/gopath/src/github.com/hyperledger/fabric/
            # - ../crypto-config/:/var/hyperledger/config
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/msp:/var/hyperledger/msp
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls:/var/hyperledger/tls
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org3.example.com/users:/var/hyperledger/users
            - /var/mynetwork/certs/config/:/var/hyperledger/config
        command: peer node start
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        depends_on:
            - couchdb0_org3
        networks:
          hlf_multi_host_network:
            aliases:
                - peer0.org3.example.com
        ports:
          - 11051:7051
          - 11053:7053

    peer1_org3:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == ip-172-31-1-154
                    - engine.labels.aws.region == ap-south-1
        image: hyperledger/fabric-peer:amd64-1.4.4
        hostname: peer1.org3.example.com
        environment:
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_PEER_NETWORKID=hlf_multi_host_network
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hlf_multi_host_network
            - CORE_PEER_ADDRESSAUTODETECT=true
            - CORE_PEER_PROFILE_ENABLED=true
            - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
            - FABRIC_LOGGING_SPEC=INFO
            - CORE_LOGGING_GOSSIP=${CORE_LOGGING_GOSSIP}
            - CORE_LOGGING_MSP=CRITICAL
            # TLS settings
            - CORE_PEER_TLS_ENABLED=true
            - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
            - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
            - CORE_PEER_CHAINCODELISTENADDRESS=peer1.org3.example.com:7052
            - CORE_PEER_ID=peer1.org3.example.com
            - CORE_PEER_ADDRESS=peer1.org3.example.com:7051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org3.example.com:7051
            - CORE_PEER_LOCALMSPID=Org3MSP
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1_org3:5984
        volumes:
            - /var/run/:/host/var/run/
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org3.example.com/peers/peer1.org3.example.com/msp:/var/hyperledger/msp
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org3.example.com/peers/peer1.org3.example.com/tls:/var/hyperledger/tls
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org3.example.com/users:/var/hyperledger/users
            - /var/mynetwork/certs/config/:/var/hyperledger/config
        command: peer node start
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        depends_on:
            - couchdb1_org3
        ports:
          - 12051:7051
          - 12053:7053
        networks:
          hlf_multi_host_network:
            aliases:
                - peer1.org3.example.com
